import type { Locale } from "@/config/locales";

const copy = {
  pt: {
    government: "República da Guiné-Bissau",
    authority: "Administração dos Portos da Guiné-Bissau",
    menu: "Menu",
    gallery: "Galeria",
    documents: "Documentos",
    admin: "Administração",
    explore: "Explorar",
    readMore: "Ver informação",
    services: "Serviços portuários",
    servicesIntro: "Acesso directo à informação que apoia as operações no Porto de Bissau.",
    institutional: "Uma autoridade portuária ao serviço do país",
    institutionalBody:
      "A APGB gere a principal porta marítima da Guiné-Bissau. O nosso trabalho liga operadores, instituições e cidadãos a serviços portuários essenciais.",
    projects: "Projectos prioritários",
    projectsIntro: "Intervenções para aumentar a capacidade, a segurança e a eficiência do porto.",
    latest: "Informação em destaque",
    latestIntro: "Notícias, documentos e actualizações da actividade portuária.",
    viewAll: "Ver tudo",
    photoArchive: "O porto em imagens",
    photoArchiveIntro: "Pessoas, infra-estruturas e actividade real no Porto de Bissau.",
    footerText:
      "Autoridade responsável pela administração, exploração e desenvolvimento dos portos da Guiné-Bissau.",
    quickLinks: "Acesso rápido",
    contact: "Contactos",
    rights: "Portal oficial da APGB",
    home: "Início",
    publishedInPt: "Conteúdo disponível em português enquanto aguarda tradução.",
    related: "Na mesma área",
    availableDocuments: "Documentos disponíveis",
    openDocument: "Abrir documento",
    currentInfo: "Informação actual",
    allPhotos: "Todas as fotografias",
    allDocuments: "Biblioteca documental",
    searchDocuments: "Documentos públicos organizados para consulta.",
    operational: "Operação",
    publicService: "Serviço público",
    safety: "Segurança",
    maritimeAccess: "Acesso marítimo",
  },
  fr: {
    government: "République de Guinée-Bissau",
    authority: "Administration des Ports de Guinée-Bissau",
    menu: "Menu",
    gallery: "Galerie",
    documents: "Documents",
    admin: "Administration",
    explore: "Explorer",
    readMore: "Voir l'information",
    services: "Services portuaires",
    servicesIntro: "Accès direct aux informations qui soutiennent les opérations du Port de Bissau.",
    institutional: "Une autorité portuaire au service du pays",
    institutionalBody:
      "L'APGB gère la principale porte maritime de la Guinée-Bissau et relie opérateurs, institutions et citoyens.",
    projects: "Projets prioritaires",
    projectsIntro: "Interventions pour renforcer la capacité, la sécurité et l'efficacité du port.",
    latest: "Informations en vedette",
    latestIntro: "Actualités, documents et mises à jour de l'activité portuaire.",
    viewAll: "Voir tout",
    photoArchive: "Le port en images",
    photoArchiveIntro: "Personnes, infrastructures et activité réelle au Port de Bissau.",
    footerText:
      "Autorité responsable de l'administration, de l'exploitation et du développement des ports de Guinée-Bissau.",
    quickLinks: "Accès rapide",
    contact: "Contacts",
    rights: "Portail officiel de l'APGB",
    home: "Accueil",
    publishedInPt: "Contenu disponible en portugais en attendant la traduction.",
    related: "Dans la même section",
    availableDocuments: "Documents disponibles",
    openDocument: "Ouvrir le document",
    currentInfo: "Information actuelle",
    allPhotos: "Toutes les photographies",
    allDocuments: "Bibliothèque documentaire",
    searchDocuments: "Documents publics organisés pour consultation.",
    operational: "Opération",
    publicService: "Service public",
    safety: "Sécurité",
    maritimeAccess: "Accès maritime",
  },
  en: {
    government: "Republic of Guinea-Bissau",
    authority: "Administration of the Ports of Guinea-Bissau",
    menu: "Menu",
    gallery: "Gallery",
    documents: "Documents",
    admin: "Administration",
    explore: "Explore",
    readMore: "View information",
    services: "Port services",
    servicesIntro: "Direct access to information supporting operations at the Port of Bissau.",
    institutional: "A port authority serving the country",
    institutionalBody:
      "APGB manages Guinea-Bissau's main maritime gateway and connects operators, institutions and citizens.",
    projects: "Priority projects",
    projectsIntro: "Interventions to improve port capacity, safety and efficiency.",
    latest: "Featured information",
    latestIntro: "News, documents and updates from port activity.",
    viewAll: "View all",
    photoArchive: "The port in pictures",
    photoArchiveIntro: "People, infrastructure and real activity at the Port of Bissau.",
    footerText:
      "Authority responsible for the administration, operation and development of Guinea-Bissau's ports.",
    quickLinks: "Quick access",
    contact: "Contacts",
    rights: "Official APGB portal",
    home: "Home",
    publishedInPt: "Content is available in Portuguese while translation is pending.",
    related: "In the same section",
    availableDocuments: "Available documents",
    openDocument: "Open document",
    currentInfo: "Current information",
    allPhotos: "All photographs",
    allDocuments: "Document library",
    searchDocuments: "Public documents organised for consultation.",
    operational: "Operations",
    publicService: "Public service",
    safety: "Safety",
    maritimeAccess: "Maritime access",
  },
} as const;

export function getUi(locale: Locale) {
  return copy[locale];
}
